[package]
name = "better-zsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
phf = { version = "0.10.1", features = ["macros"] }
fstrings = "0.2.3"

